version: 2
updates:
  - package-ecosystem: npm
    directory: /next-js
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /tailwind
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /resume
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /resume/jsonresume-theme-andrewwestling
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
