version: 2
updates:
  - package-ecosystem: npm
    directory: /next-js
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /tailwind
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /resume
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /resume/jsonresume-theme-andrewwestling
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
