title: andrewwestling.com
author: Andrew M Westling
email: a@andrewwestling.com

baseurl: ""
url: "http://andrewwestling.com"
permalink: /post/:title
google_analytics: UA-53388698-1

markdown: kramdown
theme: minima
minima:
  date_format: "%Y%m%d"
show_excerpts: true
header_pages:
  - about.md

