title: andrewwestling.com
author: Andrew M Westling
location: Brooklyn, NY
email: a@andrewwestling.com
description: Andrew M Westling is a software engineer in New York City.

baseurl: ""
url: "http://andrewwestling.com"
permalink: /posts/:title
google_analytics: UA-53388698-1

twitter_username: andwest
github_username:  expandrew
instagram_username: expandrew
linkedin_username: andrewwestling
lastfm_username: andwest
spotify_username: "1283883"
keybase_username: andrewwestling

plugins:
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
minima:
  date_format: "%Y%m%d"
show_excerpts: true
header_pages:
  - about.md

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
